version: '3.8'

services:
  web:
    build: .
    container_name: donasi-web
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - donasi_instance:/app/instance
      - donasi_static:/app/app/static
    networks:
      - shared-network

volumes:
  donasi_instance:
  donasi_static:

networks:
  shared-network:
    external: true