"""Initial database migration

Revision ID: 59b4f0b9be31
Revises: 
Create Date: 2025-08-17 19:25:24.798222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b4f0b9be31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perpus_desa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('desa', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjek_buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_perpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perpus_id', sa.Integer(), nullable=False),
    sa.Column('penanggung_jawab', sa.String(length=100), nullable=False),
    sa.Column('foto_perpus', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('latar_belakang', sa.String(length=255), nullable=False),
    sa.Column('jumlah_koleksi', sa.Integer(), nullable=True),
    sa.Column('jumlah_eksemplar', sa.Integer(), nullable=True),
    sa.Column('jam_operasional_mulai', sa.Time(), nullable=True),
    sa.Column('jam_operasional_selesai', sa.Time(), nullable=True),
    sa.Column('koleksi_buku', sa.String(length=255), nullable=True),
    sa.Column('lokasi', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kebutuhan_koleksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perpus_id', sa.Integer(), nullable=False),
    sa.Column('prioritas', sa.String(length=20), nullable=False),
    sa.Column('lokasi', sa.Text(), nullable=True),
    sa.Column('alasan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=True),
    sa.Column('tanggal_pengajuan', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perpus_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayat_distribusi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perpus_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('bukti_foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('perpus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('detail_kebutuhan_koleksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kebutuhan_id', sa.Integer(), nullable=False),
    sa.Column('subjek_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_buku', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kebutuhan_id'], ['kebutuhan_koleksi.id'], ),
    sa.ForeignKeyConstraint(['subjek_id'], ['subjek_buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=100), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('metode', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tanggal_pengiriman', sa.DateTime(), nullable=True),
    sa.Column('sampul_buku', sa.String(length=255), nullable=True),
    sa.Column('bukti_pengiriman', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sertifikat', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kegiatan_perpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perpus_id', sa.Integer(), nullable=False),
    sa.Column('nama_kegiatan', sa.String(length=200), nullable=False),
    sa.Column('tanggal_kegiatan', sa.Date(), nullable=False),
    sa.Column('deskripsi_kegiatan', sa.Text(), nullable=False),
    sa.Column('lokasi_kegiatan', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('foto_kegiatan', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perpus_id'], ['perpus_desa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donasi_id', sa.Integer(), nullable=False),
    sa.Column('subjek_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('diterima', sa.Integer(), nullable=False),
    sa.Column('ditolak', sa.Integer(), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('alasan_ditolak', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donasi_id'], ['donasi.id'], ),
    sa.ForeignKeyConstraint(['subjek_id'], ['subjek_buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_riwayat_distribusi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribusi_id', sa.Integer(), nullable=False),
    sa.Column('donasi_id', sa.Integer(), nullable=False),
    sa.Column('subjek_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distribusi_id'], ['riwayat_distribusi.id'], ),
    sa.ForeignKeyConstraint(['donasi_id'], ['donasi.id'], ),
    sa.ForeignKeyConstraint(['subjek_id'], ['subjek_buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_riwayat_distribusi')
    op.drop_table('detail_donasi')
    op.drop_table('kegiatan_perpus')
    op.drop_table('donasi')
    op.drop_table('detail_kebutuhan_koleksi')
    op.drop_table('user')
    op.drop_table('riwayat_distribusi')
    op.drop_table('kunjungan')
    op.drop_table('kebutuhan_koleksi')
    op.drop_table('detail_perpus')
    op.drop_table('subjek_buku')
    op.drop_table('perpus_desa')
    # ### end Alembic commands ###
